export default {
    ConfigHC: {
        loginHC: "ConfigHC/loginHC",
        getInfo: "ConfigHC/getInfo",
        getWifiList: "ConfigHC/getWifiList",
        configWifi: "ConfigHC/configWifi",
        configLAN: "ConfigHC/configLAN",
        firmwareUpdate: "ConfigHC/firmwareUpdate",
        reboot: "ConfigHC/reboot",
        reset: "ConfigHC/reset",
        configTimezone: "ConfigHC/configTimezone",
        resetData: "ConfigHC/resetData",
    },
    Customer: {
        forgotPassbyEmail: "Customer/forgotPassbyEmail",
        info: "Customer/info",
        updateProfile: "Customer/updateProfile",
        updateProfileConfirm: "Customer/updateProfileConfirm",
        changePass: "Customer/changePass",
        forgotPassbyPhone: "Customer/forgotPassbyPhone",
        forgotPassConfirmbyEmail: "Customer/forgotPassConfirmbyEmail",
        forgotPassConfirmbyPhone: "Customer/forgotPassConfirmbyPhone",
        resetPass: "Customer/resetPass",
        resetData: "Customer/resetData",
    },
    ContentManager: {
        setPageLoading: "ContentManager/setPageLoading",
        setCurrentSpeaker: "ContentManager/setCurrentSpeaker",
        resetData: "ContentManager/resetData",
    },
    HCMusic: {
        getPlayListUSB: "HCMusic/getPlayListUSB",
        playUsbDisk: "HCMusic/playUsbDisk",
        getTopPlayListOnline: "HCMusic/getTopPlayListOnline",
        getOnlineMusicSearch: "HCMusic/getOnlineMusicSearch",
        getOnlineSongInfo: "HCMusic/getOnlineSongInfo",
        getRealKey: "HCMusic/getRealKey",
        resetData: "HCMusic/resetData",
    },
    Home: {
        getListHomeByUserID: "Home/getListHomeByUserID",
        getMyAddress: "Home/getMyAddress",
        getNearAddress: "Home/getNearAddress",
        addAndUpdateHome: "Home/addAndUpdateHome",
        deleteHome: "Home/deleteHome",
        deleteHomeConfirm: "Home/deleteHomeConfirm",
        resetFactory: "Home/resetFactory",
        resetFactoryConfirm: "Home/resetFactoryConfirm",
        resetData: "Home/resetData",
    },
    HomeConfig: {
        getListHomeConfigByHomeID: "HomeConfig/getListHomeConfigByHomeID",
        getListHomeConfigByHomeIDNoAnimation: "HomeConfig/getListHomeConfigByHomeIDNoAnimation",
        //devices
        addDevices: "HomeConfig/addDevices",
        addDevicesRemotesInRoom: "HomeConfig/addDevicesRemotesInRoom",
        updateDevice: "HomeConfig/updateDevice",
        updateDevices: "HomeConfig/updateDevices",
        syncDevices: "HomeConfig/syncDevices",
        removeDevices: "HomeConfig/removeDevices",
        changeNameDeivce: "HomeConfig/changeNameDeivce",
        changeNameRemote: "HomeConfig/changeNameRemote",
        changeIconDevices: "HomeConfig/changeIconDevices",
        onAddIR: "HomeConfig/onAddIR",
        changeDeviceStatus: "HomeConfig/changeDeviceStatus",
        addIRinHome: "HomeConfig/addIRinHome",
        deleteSelectRemote: "HomeConfig/deleteSelectRemote",
        //floors
        addFloors: "HomeConfig/addFloors",
        updateFloor: "HomeConfig/updateFloor",
        deleteFloor: "HomeConfig/deleteFloor",
        //rooms
        addRooms: "HomeConfig/addRooms",
        updateRoom: "HomeConfig/updateRoom",
        deleteRoom: "HomeConfig/deleteRoom",
        //groups
        addGroups: "HomeConfig/addGroups",
        updateGroup: "HomeConfig/updateGroup",
        deleteGroup: "HomeConfig/deleteGroup",
        //remotes
        updateRemote: "HomeConfig/updateRemote",
        //rules
        createRule: "HomeConfig/createRule",
        updateRule: "HomeConfig/updateRule",
        deleteRule: "HomeConfig/deleteRule",
        //cameras
        addCameras: "HomeConfig/addCameras",
        updateCamera: "HomeConfig/updateCamera",
        deleteCamera: "HomeConfig/deleteCamera",
        addCameraLicence: "HomeConfig/addCameraLicence",

        resetData: "HomeConfig/resetData",
    },
    HomeControll: {
        pushControllToThing: "HomeControll/pushControllToThing",
        getListDevicesStatus: "HomeControll/getListDevicesStatus",
        controllDevice: "HomeControll/controllDevice",
        controllRule: "HomeControll/controllRule",
        controllGroup: "HomeControll/controllGroup",
        wakeupDevices: "HomeControll/wakeupDevices",
        pushControllToThingNoAnimation: "HomeControll/pushControllToThingNoAnimation",
        resetData: "HomeControll/resetData",
    },
    IrRemote: {
        getRemote: "IrRemote/getRemote",
        resetData: "IrRemote/resetData",
    },
    IrTemplate: {
        getIrAC: "IrTemplate/getIrAC",
        getIrFan: "IrTemplate/getIrFan",
        getIrSTB: "IrTemplate/getIrSTB",
        getIrTV: "IrTemplate/getIrTV",
        resetData: "IrTemplate/resetData",
    },
    LocalData: {
        getWeatherFromLocation: "LocalData/getWeatherFromLocation",
        resetData: "LocalData/resetData",
    },
    Log: {
        getLogDevice: "Log/getLogDevice",
        resetData: "Log/resetData",
    },
    Mac: {
        addHCToHome: "Mac/addHCToHome",
        checkHCNetwork: "Mac/checkHCNetwork",
        resetData: "Mac/resetData",
    },
    Media: {
        uploadFile: "Media/uploadFile",
        resetData: "Media/resetData",
    },
    Notify: {
        getNotifyList: "Notify/getNotifyList",
        readNotify: "Notify/readNotify",
        readAllNotify: "Notify/readAllNotify",
        resetData: "Notify/resetData",
    },
    User: {
        login: "User/login",
        registerGetVerifyCode: "User/registerGetVerifyCode",
        registerConfirm: "User/registerConfirm",
        logout: "User/logout",
        refreshToken: "User/refreshToken",
        resetData: "User/resetData",
    },
    Socket: {
        connect: "Socket/connect",
        disconnect: "Socket/disconnect",
        joinRoom: "Socket/joinRoom",
        leavingRoom: "Socket/leavingRoom",
        listenError: "Socket/listenError",
        listenErrorSys: "Socket/listenErrorSys",
        listenSystem: "Socket/listenSystem",
        listenStatus: "Socket/listenStatus",
        listenConfig: "Socket/listenConfig",
        resetData: "Socket/resetData",
    },
    RuleManager: {
        setRule: "RuleManager/setRule",
        resetData: "RuleManager/resetData",
    },
    CameraManager: {
        getSnapShot: "CameraManager/getSnapShot",
        addCameraStream: "CameraManager/addCameraStream",
        stopCameraStream: "CameraManager/stopCameraStream",
        deleteCameraStream: "CameraManager/deleteCameraStream",
        historyCameraStream: "CameraManager/historyCameraStream",
        resetData: "CameraManager/resetData",
    }
}
