/**
* Created by nghinv on Wed Aug 08 2018
* Copyright (c) 2018 nghinv@luci.vn
*/

import LocalizedStrings from 'react-native-localization';

const langs = new LocalizedStrings({
  en: {
    deviceOnOff: 'Switch',
    deviceDimmer: 'Dimmer',
    deviceFan: 'Fan',
    deviceCurtain: 'Curtain',
    deviceIR: 'Remote',
    deviceRGB: 'RGB',
    deviceSensor: 'sensor',
    deviceGarSensor: 'Gas sensor',
    deviceBatterySensor: 'Battery sensor',
    deviceMotionSensor: 'Motion sensor',
    deviceDoorSensor: 'Door sensor',
    deviceTempSensor: 'Temperature sensor',
    devicePowerSensor: 'Power sensor',
    deviceHumiditySensor: 'Humidity sensor',
    deviceLightSensor: 'Light sensor',
    deviceVoltageSensor: 'Voltage sensor',
    deviceCurrentSensor: 'Current sensor',
    deviceHeatSensor: 'Heat sensor',
    devicePebbleSensor: 'Pebble sensor',
    deviceWatterSensor: 'Water sensor',
    deviceSmokeSensor: 'Smoke sensor',
    deviceCOSensor: 'CO sensor',
    deviceVirSensor: 'Vibration sensor',
    deviceDoorLock: 'Door lock',
    deviceDaikin: 'Daikin',
    namecanh1: 'default',
    namecanh2: 'Afternoon',
    namecanh3: 'Clock',
    namecanh4: 'GoHome',
    namecanh5: 'GoOut',
    namecanh6: 'Home',
    namecanh7: 'Morning',
    namecanh8: 'Night',
    namecanh9: 'Noon',
    namecanh10: 'Security',
    namecanh11: 'Safe',
    namecanh12: 'Sleep',
    namecanh13: 'Travel',
    namecanh14: 'Warning',
    namecanh15: 'Movie',
    namecanh16: 'Welcome',
    namecanh17: 'WorkingTrips',
    statusOn: 'On',
    statusOff: 'Off',
    loading: 'Loading',
    speedTitle: 'Speed',
    stopTitle: 'Stop',
    levelTitle: 'Level',
    colorTitle: 'Brightness',
    detailDevice: 'Detail device',
    infomation: 'Information',
    name: 'Name',
    deviceName: 'Device name',
    type: 'Type',
    netID: 'Net ID',
    icon: 'Icon',
    network: 'Network',
    editNameDevice: 'Edit device name',
    inputNameDevice: 'Input device name',
    deviceSetting: 'Device setting',
    done: 'Done',
    deleteDevice: 'Delete device',
    cancel: 'Cancel',
    statusLock: 'Lock',
    statusUnlock: 'Unlock',
    mode: 'Mode',
    fan: 'Fan',
    hasGar: 'Active',
    normal: 'Normal',
    motionDetect: 'Active',
    noMotion: 'Inactive',
    doorOpen: 'Open',
    doorClose: 'Close',
    hasWatter: 'Active',
    hasSmoke: 'Active',
    hasVibration: 'Vibration',
    pebbleStatus: [
      'None',
      'Rotate Right',
      'Rotate Left',
      'Swipe Up',
      'Swipe Down',
      'Swipe Left',
      'Swipe Right',
      'Hold',
      'Tap',
      'Double Tap',
      '3 Press',
      '4 Press',
      '5 Press',
      '6 Press',
      '7 Press',
      'Press 1 time EP1',
      'Press 2 time EP1',
      'Hold EP1',
      'Press 1 time EP2',
      'Press 2 time EP2',
      'Hold EP2',
      'Press 1 time EP3',
      'Press 2 time EP3',
      'Hold EP3',
    ],
    statusOpen: 'Opened',
    statusClose: 'Closed',
    inputTitle: 'Input level',
    moreColor: 'More color',
    selectColor: 'Select color',
    statusDevice: 'Status',
    irType: ['TV', 'Fan', 'Air Condition', 'Amply 1', 'Amply 2'],
    removeDevice: 'Remove device',
    rejoinDevice: 'Rejoin network',
    addIR: 'Add ir',
    deleteIR: 'Delete IR',
    learnCommand: 'Learn command',
    removeCommand: 'Remove command',
    learning: 'Learning...',
    unKnow: 'Unknown',
    successRemoveDevice: 'Remove device successful',
    successEditNameDevice: 'Edit name of device successful',
    successEditIconDevice: 'Edit icon of device successful',
    'ic-zw-switch': 'On/Off Power Switch',
    'ic-zw-power-strip': 'Socket',
    'ic-zw-siren': 'Siren',
    'ic-zw-valve': 'Valve – open/close',
    'ic-zw-irrigation-control': 'Irrigation Control',
    'ic-zw-dimmer': 'Light Dimmer Switch',
    'ic-zw-rgb': 'RGBW',
    'ic-zw-fan': 'Fan Switch',
    'device-curtain-horizontal-0': 'Curtain horizontal',
    'cutain-vertical-0': 'Curtain vertical',
    'cutain-screen-0': 'Screen',
    'ic-zw-window-covering-endpoint-aware-01': 'Window Covering Endpoint Aware',
    'ic-zw-window-covering-endpoint-aware-02': 'Window Covering Position/Endpoint Aware',
    'ic-zw-door-lock-keypad': 'Door lock - Keypad',
    'ic-zw-co-alarm': 'CO Alarm',
    'ic-zw-gas-alarm': 'Gas Alarm',
    'ic-zw-heat-alarm': 'Heat Alarm',
    'ic-zw-luminace': 'Luminance',
    'ic-zw-power-management-100': 'Power Management',
    'ic-zw-security-door': 'Access Control',
    'ic-zw-sencer-motion': 'Home Security',
    'ic-zw-smoke-alarm': 'Smoke Alarm',
    'ic-zw-water-alarm': 'Water Alarm',
    'ic-zw-thermostat': 'Thermostat - HVAC',
    'ic-zw-metter': 'Sub Energy Meter',
    'ic-zw-light-bulb': 'Bulb',
    'ic-zw-bell': 'Bell',
    'ic-zw-camera': 'Camera',
    'ic-zw-chandelier': 'Chandelier',
    'ic-zw-church-lamp': 'Church lamp',
    'ic-zw-compact': 'Compact',
    'ic-zw-decorative-light': 'Decorative light',
    'ic-zw-down-light': 'Downlight',
    'ic-zw-drop-light': 'Droplight',
    'ic-zw-fluorescent': 'Fluorescent',
    'ic-zw-gate': 'Gate',
    'ic-zw-led': 'Led',
    'ic-zw-light-pole': 'Pole light',
    'ic-zw-motor': 'Motor',
    'ic-zw-night-light': 'Night light',
    'ic-zw-overhead-light': 'Overhead',
    'ic-zw-speaker': 'Speaker',
    'ic-zw-tv': 'TV',
    'ic-zw-wall-light': 'Wall light',
    'ic-zw-heating-lamp': 'Heating lamp',
    'ic-zw-ic-zw-IrrigationValve': 'Irrigation Valve',
    'ic-zw-ventilator': 'Ventilator',
    'ic-zw-water-heater': 'Water heater',
    wifi: 'Wifi',
    mic: 'Mic',
    'icon-ir2-ac': 'Air Condition',
    mac: 'MAC',
    version: 'Version',
    hcManager: 'HC manager',
    room: 'Room',
    online: 'Online',
    offline: 'Offline',
    changeIcon: 'Change icon',
    inputSearch: 'Search device',
    deviceTypeSwitch: 'Switch',
    deviceTypeLight: 'Light dimmer',
    deviceTypeFan: 'Fan',
    deviceTypeCurtain: 'Curtain',
    deviceTypeDoorlock: 'Doorlock',
    deviceTypeSensor: 'Sensor',
    deviceTypeDaikin: 'Daikin',
    deviceTypePebble: 'Pebble',
    deviceTypeBattery: 'Battery',
    deviceTypeUnknow: 'Unknow',
    allTypeDevice: 'All device',
    lightRGB: 'Light',
    notification: 'Notification',
    confirmWakeupDevice: 'Lost device connection. Do you want to reconnect to the device?',
    confirmDeleteDevice: 'Do you want to delete the device?',
    confirm: 'Confirm',
    titleLoading: 'Processing...',
    changeState: 'Select state',
    deviceSpeaker: ['Play', 'Pause', 'Next', 'Prew'],
    selectTypePlaySpeaker: 'Select type action',
    addAction: 'Add action',
    addMusic: 'Add music',
    addVolume: 'Add volume',
    addChannel: 'Add channel',
    volume: 'Volume',
    channel: 'Channel',
    music: 'Music',
    channelSpeaker: ['Left', 'Right', 'Left-Right'],
    selectMusic: 'Select music',
    changeMusic: 'Change music',
    speaker: 'Speaker',
    remoteLearnCommand: 'Remote learning command',
    addIrTV: 'Add ir television',
    addIrFan: 'Add ir fan',
    AddIrAir: 'Add ir air condition',
    noMusic: 'No music',
    deleteCommand: 'Delete command',
    remoteRemoveCommand: 'Remote removing command',
    skip: 'Skip',
    timeoutLeaning: 'Timeout learn command',
    timeoutDeleteCommand: 'Timeout delete command',
    errorLearnCommand: 'Error learn command',
    errorDeleteCommand: 'Error delete command',
    addDetailIr: 'Command info',
    temp: 'Temp',
    modeAirIR: 'Mode',
    fanAirIr: 'Fan mode',
    swingAirIr: 'Swing mode',
    command: 'Command',
    selectCommand: 'Select command',
    irOn: 'On',
    irOff: 'Off',
    irOnOff: 'On/Off',
    irAuto: 'Auto',
    irSpeed: 'Speed',
    irSwing: 'Swing',
    irTimer: 'Timer',
    irChannel0: 'Channel 0',
    irChannel1: 'Channel 1',
    irChannel2: 'Channel 2',
    irChannel3: 'Channel 3',
    irChannel4: 'Channel 4',
    irChannel5: 'Channel 5',
    irChannel6: 'Channel 6',
    irChannel7: 'Channel 7',
    irChannel8: 'Channel 8',
    irChannel9: 'Channel 9',
    irChannelDown: 'Channel down',
    irChannelUp: 'Channel Up',
    irExit: 'Exit',
    irInfo: 'Info',
    irInput: 'Input',
    irList: 'List',
    irMenu: 'Menu',
    irMenuDown: 'Menu down',
    irMenuLeft: 'Menu left',
    irMenuOK: 'Menu OK',
    irMenuRight: 'Menu right',
    irMenuUp: 'Menu up',
    irPower: 'Power',
    irVolDown: 'Volume down',
    irVolumeUp: 'Volume up',
    irMute: 'Mute',
    irSmartHub: 'Smart hub',
    irEnter: 'Enter',
    continue: 'Continue',
    addNewDevice: 'ADD NEW DEVICE',
    musicFromHC: 'Music from HCs',
    musicFromSpeaker: 'Music from speaker SD card',
    infomationSecurity: 'Extract security infomation...',
    warningSelectLevelSecurity: 'Warning: Only experienced user, who knows the concept of Z-Wave security class, should change security class settings. Notice: Should choose highest security level for devices Door locks, garage doors',
    matchSecurityCode: 'Match security code...',
    txtInputSecurityCode: 'Fill the first 5 digits from the device label. The other 7*5 digits in device label should match the numbers below.',
    closing: 'Closing',
    stopping: 'Stopping',
    opening: 'Opening',
    configDevices: 'Config Devices',
    listHC: 'List HC',
    listDevices: 'List devices',
    chooseTypeConnect: 'Type connect',
    otherFloor: 'New',
    on: 'On',
    off: 'Off',
    open: 'Open',
    close: 'Close',
    haveSelect: 'Selected',
    devices: 'Devices',
    addDeviceToRoom: 'Add to room',
    addDeviceToRoomSuccess: 'Add device to room success',
    chooseControl: 'Choose Remote Type',
    remoteType: 'Remote type',
    selectManufacturer: 'Select manufacturer',
    manufacture: 'Manufacturer',
    setting: 'Setting',
    askControlIr: 'Does the device receive control signals?',
    noTitle: 'No',
    yesTitle: 'Yes',
    addNameDevice: 'Add name device',
    ok: 'OK',
    errorNameIsNull: 'Name can not be empty',
    errorNameHasSymbol: 'Name can not contain special characters',
    advanced: 'Advanced Setting',
    configuration: 'Configuration',
    warning: 'Warning',
    // eslint-disable-next-line no-useless-escape
    warningConfigAddParameter: 'This function will send Configuration Command to devices.\nBattery device or Sleeping device should be wake up manually after \"Save Configuration\" in order for the Controller to start the configuration process.',
    configuaration: 'Configuration',
    addParameter: 'Add parameter',
    config: 'Configuration',
    defaultValue: 'Default value',
    delete: 'Delete',
    notify: 'Notification',
    errorAddParamId: 'You need add ID',
    errorAddParamValue: 'You need add Value',
    irFan: 'Fan',
    parameter: 'Parameter',
    errorAddSameParameter: 'The parameter already exists',
    save: 'SAVE',
    camera: 'Camera',
    lineDetection: 'Line detection',
    fieldDetection: 'Field detection',
    sceneChangeDetection: 'Scene change detection',
    userCode: 'User code',
    log: 'Log',
    securityDevice: 'Security device',
    turnOffPin: 'Turn off PIN',
    changePin: 'Change PIN',
    hadTurnOn: 'had turn on',
    hadUnlock: 'had unlock',
    hadOpen: 'had open',
    moduleInput: 'Module Input',
    virtualDevice: 'Thiết bị ảo',
    user: 'User',
    setNewPin: 'New PinCode',
    changePinCode: 'Change PinCode',
    deletePinCode: 'Delete PinCode',
    currentYourPinCodeIs: 'Your PinCode:',
    pinCode: 'PinCode',
    inputPinCode: 'Input PinCode',
    pinCodeMinLengthError: 'Pin code must have 4 or more digits',
    setPinCodeSuccess: 'Set pin code success',
    setPinCodeFailed: 'Set pin code failed',
    clearPinCodeSuccess: 'Pin code is clear',
    clearPinCodeFailed: 'Clear pin code failed',
    irHome: 'Home',
    irBack: 'Back',
    irDelete: 'Delete',
    irPageUp: 'PageUp',
    irPageDown: 'PageDown',
    vibration: 'Vibration',
    tilt: 'Tilt',
    fall: 'Fall',
    fanSpeed: 'Fan speed',
    swing: 'Swing',
    modeIr: 'Mode',
    onOff: 'On/Off',
    execution: 'Execution',
    brightness: 'Brightness',
    warm: 'Warm',
    white: 'White',
    doorLockSetting: 'Door lock settings',
    userPinCode: 'User PIN code',
    oneTimeUserCode: 'Onetime User Code',
    fingerprint: 'Fingerprint',
    language: 'Language',
    autoLocking: 'Auto locking',
    listUser: 'List Users',
    username: 'Username',
    listFingerprint: 'ListFingerprint',
    history: 'History',
    event: 'Events',
    lockAction: {
      locked: 'Lock',
      unlocked: 'Unlock',
      setPin: 'Set PIN Code',
      deletePin: 'Delete PIN Code',
      setFp: 'Set Fingerprint',
      deleteFp: 'Delete Fingerprint',
      unlockIllegal: 'Unlock illegal',
      lowBattery: 'Low batttery',
      set: 'Set',
      get: 'Get',
      clear: 'Clear',
      getAll: 'Get all',
      verifyMasterCode: 'Verify master code',
      warning: 'Warning',
      addPinCode: 'Add new User PIN Code',
      addMasterCode: 'Add new Master Code',
      addOnetimeCode: 'Add new Onetime Code',
      deletePinCode: 'Delete User PIN Code',
      deleteMasterCode: 'Delete Master Code',
      deleteOnetimeCode: 'Delete Onetime Code',
      lockAuto: 'Automation lock',
      unlockAuto: 'Automation unlock',
      addFingerPrint: 'Add new FingerPrint',
      deleteFingerPrint: 'Delete FingerPrint',
      setPinCode: 'Set User PIN Code',
      setMasterCode: 'Set Master Code',
      setOneTimeCode: 'Set Onetime Code',
      setFingerprint: 'Set Fingerprint'
    },
    lockSource: {
      byApp: 'by App',
      byHand: 'by Hand',
      byDevice: 'by Device',
      withFingerPrint: 'with FingerPrint',
      withMasterCode: 'with Master Code',
      withOnetimeCode: 'with Onetime Code',
      byPincode: 'with User PIN Code',
      fromDevice: 'by device'
    },
    by: 'by',
    nodata: 'No data',
    pincode: 'Pin code',
    inputUsername: 'Input username',
    inputPincode: 'Input pin code',
    saveChange: 'Save Change',
    deviceYaleLock: 'Yale lock',
    license: 'License',
    unActive: 'Unactive',
    active: 'Active',
    unAddSeriNumber: 'Need add serial number',
    setUsernameSuccess: 'Set username success',
    setUsernameFailed: 'Set username failed',
    setFingerPrint: 'Set fingerprint',
    waitForSetFingerprintSuccess: 'Place your finger on the fingerprint sensor area on the lock to confirm it',
    setFingerPrintSuccess: 'Set fingerprint success',
    setFingerPrintFailed: 'Set fingerprint failed',
    savePincode: 'Save onetime code',
    clearPinCode: 'Clear onetime code',
    clearOnetimeCodeSuccess: 'Clear onetime code success',
    clearOneTimecodeFailed: 'Clear onetime code failed',
    lockUnactive: 'Active lock first!',
    activeNow: 'Active now',
    passwordGreater3Charactor: 'The password must to greater than 3 characters',
    scene: 'Scenes',
    status: 'Status',
    moreOption: 'More option',
    next: 'Next',
    byUser: 'by',
    pinCodeUsed: 'Pincode had use',
    masterCode: 'Master code',
    modeActive: 'Mode',
    sortDevices: 'Sort devices',
    activity: 'Activity',
    logDetail: 'Detail',
    typeExecution: {
      onOff: 'On Off',
      colorSpectrum: 'Color Spectrum',
      coldWarmColor: 'Cold Warm Color',
      brightness: 'Brightness',
      modeActive: 'Mode Active'
    },
    chooseTypeControl: 'Choose type control',
    sourceControl: {
      app: 'App',
      rule: 'Rule',
      scene: 'Scene',
      physical: 'Physical',
      device: 'Device',
      hand: 'Hand',
      schedule: 'Schedule',
      controlBy: 'Control by',
      from: 'from',
      group: 'Group'
    },
    normalType: 'Normal',
    selectCamera: 'Select camera',
    titleMeshNetworkReconfig: 'Update network',
    cameraPreview: 'Camera preview',
    removeCameraPreview: 'Remove camera preview',
    ruleInfo: 'Rules info',
    sceneInfo: 'Scenes info',
    groupInfo: 'Groups info'
  },
  vi: {
    deviceOnOff: 'Công tắc',
    deviceDimmer: 'Chiết áp',
    deviceFan: 'Quạt',
    deviceCurtain: 'Rèm',
    deviceIR: 'Remote',
    deviceRGB: 'RGB',
    deviceSensor: 'Cảm biến',
    deviceGarSensor: 'Cảm biến khí gar',
    deviceBatterySensor: 'Cảm biến Pin',
    deviceMotionSensor: 'Cảm biến chuyển động',
    deviceDoorSensor: 'Cảm biến cửa',
    deviceTempSensor: 'Cảm biến nhiệt độ',
    deviceHumiditySensor: 'Cảm biến độ ẩm',
    deviceLightSensor: 'Cảm biến ánh sáng',
    devicePebbleSensor: 'Pebble',
    deviceWatterSensor: 'Cảm biến nước',
    deviceSmokeSensor: 'Cảm biến khói',
    deviceCOSensor: 'Cảm biến khí CO',
    deviceVirSensor: 'Cảm biến rung',
    deviceDoorLock: 'Khoá cửa',
    deviceDaikin: 'Điều hoà Daikin',
    devicePowerSensor: 'Cảm biến công suất',
    deviceVoltageSensor: 'Cảm biến điện áp',
    deviceCurrentSensor: 'Cảm biến cường độ dòng điện',
    deviceHeatSensor: 'Cảm biến nhiệt',
    namecanh1: 'mặc định',
    namecanh2: 'Buổi chiều',
    namecanh3: 'Đồng hồ',
    namecanh4: 'Về nhà',
    namecanh5: 'Ra ngoài',
    namecanh6: 'Nhà',
    namecanh7: 'Buổi sáng',
    namecanh8: 'Buổi tối',
    namecanh9: 'buổi trưa',
    namecanh10: 'An ninh',
    namecanh11: 'An toàn',
    namecanh12: 'Đi ngủ',
    namecanh13: 'Du lịch',
    namecanh14: 'Cảnh báo',
    namecanh15: 'Xem phim',
    namecanh16: 'Chào mừng',
    namecanh17: 'Đi công tác',
    statusOn: 'Bật',
    statusOff: 'Tắt',
    loading: 'Đang thực hiện',
    speedTitle: 'Tốc độ',
    stopTitle: 'Dừng',
    levelTitle: 'Mức',
    colorTitle: 'Độ sáng',
    detailDevice: 'Chi tiết thiết bị',
    infomation: 'Thông tin',
    name: 'Tên',
    deviceName: 'Tên thiết bị',
    type: 'Loại',
    netID: 'Net ID',
    icon: 'Biểu tượng',
    network: 'Mạng',
    editNameDevice: 'Sửa tên thiết bị',
    inputNameDevice: 'Nhập tên thiết bị',
    deviceSetting: 'Cài đặt thiết bị',
    done: 'Xong',
    deleteDevice: 'Xoá thiết bị',
    cancel: 'Huỷ',
    statusLock: 'Khoá',
    statusUnlock: 'Mở',
    mode: 'Mode',
    fan: 'Fan',
    hasGar: 'Có',
    normal: 'Không',
    motionDetect: 'Có',
    noMotion: 'Không',
    doorOpen: 'Mở',
    doorClose: 'Đóng',
    hasWatter: 'Có',
    hasSmoke: 'Có',
    hasVibration: 'Rung',
    pebbleStatus: [
      'Không',
      'Xoay phải',
      'Xoay trái',
      'Vuốt lên',
      'Vuốt xuống',
      'Vuốt trái',
      'Vuốt phải',
      'Giữ',
      '1 chạm',
      '2 chạm',
      '3 chạm',
      '4 chạm',
      '5 chạm',
      '6 chạm',
      '7 chạm',
      '1 chạm EP1',
      '2 chạm EP1',
      'Giữ EP1',
      '1 chạm EP2',
      '2 chạm EP2',
      'Giữ EP2',
      '1 chạm EP3',
      '2 chạm EP3',
      'Giữ EP3',
    ],
    statusOpen: 'Mở',
    statusClose: 'Đóng',
    inputTitle: 'Nhập mức',
    moreColor: 'Chọn màu khác',
    selectColor: 'Chọn màu',
    statusDevice: 'Trạng thái',
    irType: ['Tivi', 'Quạt', 'Điều hoà', 'Amply 1', 'Amply 2'],
    removeDevice: 'Xoá thiết bị khỏi mạng',
    rejoinDevice: 'Gia nhập lại thiết bị',
    addIR: 'Thêm remote',
    deleteIR: 'Xoá remote',
    learnCommand: 'Học lệnh',
    removeCommand: 'Xoá lệnh',
    learning: 'Đang học lệnh...',
    unKnow: 'Unknow',
    successRemoveDevice: 'Xoá thiết bị khỏi nhóm thành công',
    successEditNameDevice: 'Sửa tên thiết bị thành công',
    successEditIconDevice: 'Sửa biểu tượng thiết bị thành công',
    'ic-zw-switch': 'Công tắc bật tắt',
    'ic-zw-power-strip': 'Ổ cắm',
    'ic-zw-siren': 'Còi báo động',
    'ic-zw-valve': 'Van đóng mở',
    'ic-zw-irrigation-control': 'Điều khiển tưới',
    'ic-zw-dimmer': 'Dimmer',
    'ic-zw-rgb': 'RGBW',
    'ic-zw-fan': 'Điều khiển quạt',
    'device-curtain-horizontal-0': 'Rèm ngang',
    'cutain-vertical-0': 'Rèm đứng',
    'cutain-screen-0': 'Màn chiếu',
    'ic-zw-window-covering-endpoint-aware-01': 'Rèm loại B',
    'ic-zw-window-covering-endpoint-aware-02': 'Rèm loại C',
    'ic-zw-door-lock-keypad': 'Khóa cửa',
    'ic-zw-co-alarm': 'Cảm biến CO',
    'ic-zw-gas-alarm': 'Cảm biến khí gas',
    'ic-zw-heat-alarm': 'Cảm biến nhiệt',
    'ic-zw-luminace': 'Cảm biến ánh sáng',
    'ic-zw-power-management-100': 'Cảm biến năng lượng',
    'ic-zw-security-door': 'Báo động truy cập',
    'ic-zw-sencer-motion': 'Báo động an ninh',
    'ic-zw-smoke-alarm': 'Cảm biến khói',
    'ic-zw-water-alarm': 'Cảm biến nước',
    'ic-zw-thermostat': 'Điều khiển điều hòa thường',
    'ic-zw-metter': 'Đồng hồ đo năng lượng',
    'ic-zw-light-bulb': 'Đèn sợi đốt',
    'ic-zw-bell': 'Chuông',
    'ic-zw-camera': 'Camera',
    'ic-zw-chandelier': 'Đèn chùm',
    'ic-zw-church-lamp': 'Đèn thờ',
    'ic-zw-compact': 'Đèn compact',
    'ic-zw-decorative-light': 'Đèn trang trí',
    'ic-zw-down-light': 'Downlight',
    'ic-zw-drop-light': 'Đèn thả',
    'ic-zw-fluorescent': 'Đèn tuýp',
    'ic-zw-gate': 'Cổng',
    'ic-zw-led': 'Led',
    'ic-zw-light-pole': 'Đèn cột',
    'ic-zw-motor': 'Mô tơ',
    'ic-zw-night-light': 'Đèn ngủ',
    'ic-zw-overhead-light': 'Đèn hắt',
    'ic-zw-speaker': 'Loa',
    'ic-zw-tv': 'Tivi',
    'ic-zw-wall-light': 'Đèn tường',
    'ic-zw-heating-lamp': 'Đèn sưởi',
    'ic-zw-ic-zw-IrrigationValve': 'Van tưới',
    'ic-zw-ventilator': 'Quạt thông gió',
    'ic-zw-water-heater': 'Bình nóng lạnh',
    wifi: 'Wifi',
    mic: 'Mic',
    'icon-ir2-ac': 'Điều hoà',
    mac: 'MAC',
    version: 'Phiên bản',
    hcManager: 'HC quản lý',
    room: 'Phòng',
    online: 'Online',
    offline: 'Offline',
    changeIcon: 'Biểu tượng',
    inputSearch: 'Tìm kiếm',
    deviceTypeSwitch: 'Công tắc',
    deviceTypeLight: 'Chiết áp, Rgb',
    deviceTypeFan: 'Quạt',
    deviceTypeCurtain: 'Rèm',
    deviceTypeDoorlock: 'Khoá cửa',
    deviceTypeSensor: 'Cảm biến',
    deviceTypeDaikin: 'Daikin',
    deviceTypePebble: 'Pebble',
    deviceTypeBattery: 'Cảm biến pin',
    deviceTypeUnknow: 'Không xác định',
    allTypeDevice: 'Tất cả',
    lightRGB: 'Độ sáng',
    notification: 'Thông báo',
    confirmWakeupDevice: 'Thiết bị đang mất kết nối. Bạn có muốn kết nối lại với thiết bị?',
    confirmDeleteDevice: 'Bạn chắc chắn muốn xoá thiết bị này?',
    confirm: 'Đồng ý',
    titleLoading: 'Đang thực hiện...',
    changeState: 'Chọn trạng thái',
    deviceSpeaker: ['Play', 'Pause', 'Next', 'Prew'],
    selectTypePlaySpeaker: 'Choose type action',
    addAction: 'Thêm hành động',
    addMusic: 'Thêm nhạc',
    addVolume: 'Thêm âm lượng',
    addChannel: 'Thêm kênh loa',
    volume: 'Âm lượng',
    channel: 'Kênh',
    music: 'Nhạc',
    channelSpeaker: ['Trái', 'Phải', 'Trái-Phải'],
    selectMusic: 'Chọn bài hát',
    changeMusic: 'Đổi BH',
    speaker: 'Speaker',
    remoteLearnCommand: 'Đang học lệnh IR',
    addIrTV: 'Thêm điều khiển tivi',
    addIrFan: 'Thêm điều khiển quạt',
    AddIrAir: 'Thêm điều khiển điều hoà',
    noMusic: 'Không có bài hát nào',
    deleteCommand: 'Xoá lệnh',
    remoteRemoveCommand: 'Đang xoá lệnh IR',
    skip: 'Bỏ qua',
    timeoutLeaning: 'Hết thời gian học lệnh',
    errorLearnCommand: 'Lỗi học lệnh',
    errorDeleteCommand: 'Lỗi xoá lệnh',
    addDetailIr: 'Thông tin lệnh',
    temp: 'Nhiệt độ',
    modeAirIR: 'Chế độ',
    fanAirIr: 'Mức quạt',
    swingAirIr: 'Swing mode',
    timeoutDeleteCommand: 'Hết thời gian xoá lệnh',
    command: 'Lệnh',
    selectCommand: 'Chọn lệnh',
    irOn: 'On',
    irOff: 'Off',
    irOnOff: 'On/Off',
    irAuto: 'Auto',
    irSpeed: 'Speed',
    irSwing: 'Swing',
    irTimer: 'Timer',
    irChannel0: 'Channel 0',
    irChannel1: 'Channel 1',
    irChannel2: 'Channel 2',
    irChannel3: 'Channel 3',
    irChannel4: 'Channel 4',
    irChannel5: 'Channel 5',
    irChannel6: 'Channel 6',
    irChannel7: 'Channel 7',
    irChannel8: 'Channel 8',
    irChannel9: 'Channel 9',
    irChannelDown: 'Channel down',
    irChannelUp: 'Channel Up',
    irExit: 'Exit',
    irInfo: 'Info',
    irInput: 'Input',
    irList: 'List',
    irMenu: 'Menu',
    irMenuDown: 'Menu down',
    irMenuLeft: 'Menu left',
    irMenuOK: 'Menu OK',
    irMenuRight: 'Menu right',
    irMenuUp: 'Menu up',
    irPower: 'Power',
    irVolDown: 'Volume down',
    irVolumeUp: 'Volume up',
    irMute: 'Mute',
    irSmartHub: 'Smart hub',
    irEnter: 'Enter',
    continue: 'Tiếp tục',
    addNewDevice: 'THÊM THIẾT BỊ MỚI',
    musicFromHC: 'Nhạc từ HCs',
    musicFromSpeaker: 'Nhạc từ thẻ nhớ Speaker',
    infomationSecurity: 'Trích xuất thông tin bảo mật...',
    warningSelectLevelSecurity: 'Cảnh báo: Chỉ người dùng có kinh nghiệm, người biết khái niệm lớp bảo mật Z-Wave, mới nên thay đổi cài đặt lớp bảo mật. Chú ý nên chọn mức bảo mật cao cho khoá cửa, cửa cuốn, cửa cổng',
    matchSecurityCode: 'Nhập mã bảo mật...',
    txtInputSecurityCode: 'Điền 5 chữ số đầu tiên từ nhãn thiết bị. Các chữ số 7 * 5 khác trong nhãn thiết bị phải khớp với các số bên dưới.',
    closing: 'Đang đóng',
    stopping: 'Đang dừng',
    opening: 'Đang mở',
    configDevices: 'Cài đặt thiết bị',
    listHC: 'Danh sách HC',
    listDevices: 'Danh sách thiết bị',
    chooseTypeConnect: 'Loại kết nối',
    otherFloor: 'Mới',
    on: 'Bật',
    off: 'Tắt',
    open: 'Mở',
    close: 'Đóng',
    haveSelect: 'Đã chọn',
    devices: 'Thiết bị',
    addDeviceToRoom: 'Thêm vào',
    addDeviceToRoomSuccess: 'Thêm thiết bị vào phòng thành công',
    chooseControl: 'Chọn điều khiển',
    remoteType: 'Loại điều khiển',
    selectManufacturer: 'Chọn thương hiệu',
    manufacture: 'Thương hiệu',
    setting: 'Cài đặt',
    askControlIr: 'Thiết bị có nhận được tín hiệu điều khiển không?',
    noTitle: 'Không',
    yesTitle: 'Có',
    addNameDevice: 'Thêm tên thiết bị',
    ok: 'OK',
    errorNameIsNull: 'Bạn chưa nhập tên thiết bị',
    errorNameHasSymbol: 'Tên thiết bị không được chứa kí tự đặc biệt',
    advanced: 'Cài đặt nâng cao',
    configuration: 'Cài đặt thiết bị',
    warning: 'Cảnh báo',
    // eslint-disable-next-line no-useless-escape
    warningConfigAddParameter: 'Chức năng này sẽ gửi Lệnh cấu hình tới các thiết bị. \nCác thiết bị chạy pin phải được đánh thức thủ công sau khi \"Lưu cấu hình\" để Bộ điều khiển bắt đầu quá trình cấu hình.',
    configuaration: 'Cài đặt',
    addParameter: 'Thêm parameter',
    config: 'Cài đặt',
    defaultValue: 'Đặt giá trị mặc định',
    delete: 'Xoá',
    notify: 'Thông báo',
    errorAddParamId: 'Bạn chưa thêm ID',
    errorAddParamValue: 'Bạn chưa thêm Value',
    irFan: 'Fan',
    parameter: 'Parameter',
    errorAddSameParameter: 'Parameter đã tồn tại',
    save: 'Lưu lại',
    camera: 'Camera',
    lineDetection: 'Phát hiện vượt rào',
    fieldDetection: 'Phát hiện xâm nhập',
    sceneChangeDetection: 'Phát hiện thay đổi cảnh',
    userCode: 'Người dùng',
    log: 'Log',
    securityDevice: 'Bảo mật thiết bị',
    turnOffPin: 'Tắt mã PIN',
    changePin: 'Thay đổi mã PIN',
    hadTurnOn: 'đã được bật',
    hadUnlock: 'đã được mở khoá',
    hadOpen: 'đã được mở',
    moduleInput: 'Module Input',
    virtualDevice: 'Virtual Device',
    user: 'Người dùng',
    setNewPin: 'Thêm mã pin',
    changePinCode: 'Thay đổi mã pin',
    deletePinCode: 'Xoá mã Pin',
    currentYourPinCodeIs: 'Mã pin hiện tại:',
    pinCode: 'Mã Pin',
    inputPinCode: 'Nhập mã pin',
    pinCodeMinLengthError: 'Mã pin phải có từ 4 kí tự trở lên',
    setPinCodeSuccess: 'Cài đặt mã pin thành công',
    setPinCodeFailed: 'Xảy ra lỗi khi cài đặt mã pin',
    clearPinCodeSuccess: 'Mã pin đã được xoá',
    clearPinCodeFailed: 'Xảy ra lỗi khi xoá mã pin',
    irHome: 'Home',
    irBack: 'Back',
    irDelete: 'Delete',
    irPageUp: 'PageUp',
    irPageDown: 'PageDown',
    vibration: 'Rung',
    tilt: 'Nghiêng',
    fall: 'Rơi',
    fanSpeed: 'Tốc độ gió',
    swing: 'Hướng gió',
    modeIr: 'Chế độ',
    onOff: 'Bật/Tắt',
    execution: 'Lệnh',
    brightness: 'Độ sáng',
    warm: 'Ấm',
    white: 'Sáng',
    doorLockSetting: 'Cài đặt khoá',
    userPinCode: 'Người dùng',
    oneTimeUserCode: 'Mật khẩu 1 lần',
    fingerprint: 'Vân tay',
    language: 'Ngôn ngữ',
    autoLocking: 'Tự động khoá',
    listUser: 'Danh sách người dùng',
    username: 'Tên người dùng',
    listFingerprint: 'Danh sách vân tay',
    history: 'Lịch sử',
    event: 'Sự kiện',
    lockAction: {
      locked: 'Khoá cửa',
      unlocked: 'Mở cửa',
      setPin: 'Cài đặt mã PIN',
      deletePin: 'Xoá mã PIN',
      setFp: 'Cài đặt vân tay',
      deleteFp: 'Xoá vân tay',
      unlockIllegal: 'Mở khoá bất hợp pháp',
      lowBattery: 'Pin yếu',
      set: 'Cài đặt',
      get: 'Hỏi',
      clear: 'Xoá',
      getAll: 'Hỏi tất cả',
      verifyMasterCode: 'Xác thực mã PIN',
      warning: 'Cảnh báo',
      addPinCode: 'Thêm mã PIN',
      addMasterCode: 'Thêm mã chính',
      addOnetimeCode: 'Thêm mật khẩu 1 lần',
      deletePinCode: 'Xoá mã PIN',
      deleteMasterCode: 'Xoá mã chính',
      deleteOnetimeCode: 'Xoá mật khẩu 1 lần',
      lockAuto: 'Khoá cửa tự động',
      unlockAuto: 'Mở cửa tự động',
      addFingerPrint: 'Thêm vân tay',
      deleteFingerPrint: 'Xoá vân tay',
      setPinCode: 'Cài đặt mã PIN',
      setMasterCode: 'Cài đặt mã chính',
      setOneTimeCode: 'Cài đặt mật khẩu 1 lần',
      setFingerprint: 'Cài đặt vân tay'
    },
    lockSource: {
      byApp: 'bởi ứng dụng',
      byHand: 'bằng tay',
      byDevice: 'bởi thiết bị',
      withFingerPrint: 'bằng vân tay',
      withMasterCode: 'bằng mã chính',
      withOnetimeCode: 'bằng mật khẩu một lần',
      byPincode: 'bằng mã PIN',
      fromDevice: 'từ thiết bị'
    },
    by: 'bởi',
    nodata: 'Không có dữ liệu',
    pincode: 'Mã pin',
    inputUsername: 'Nhập tên người dùng',
    inputPincode: 'Nhập mã pin',
    saveChange: 'Lưu Thay Dổi',
    deviceYaleLock: 'Khoá Yale',
    license: 'Giấy phép',
    unActive: 'Chưa kích hoạt',
    active: 'Đã kích hoạt',
    unAddSeriNumber: 'Chưa thêm số serial',
    setUsernameSuccess: 'Sửa tên người dùng thành công',
    setUsernameFailed: 'Xảy ra lỗi khi sửa tên người dùng',
    setFingerPrint: 'Cài đặt vân tay',
    waitForSetFingerprintSuccess: 'Để tay lên vùng cảm ứng vân tay trên khoá để xác nhận',
    setFingerPrintSuccess: 'Cài đặt vân tay thành công',
    setFingerPrintFailed: 'Lỗi cài đặt vân tay',
    savePincode: 'Lưu mật khẩu',
    clearPinCode: 'Xoá mật khẩu',
    clearOnetimeCodeSuccess: 'Xoá mật khẩu thành công',
    clearOneTimecodeFailed: 'Lỗi xoá mật khẩu',
    lockUnactive: 'Khoá chưa được kích hoạt',
    activeNow: 'Kích hoạt ngay',
    passwordGreater3Charactor: 'Mật khẩu phải lớn hơn 3 kí tự',
    scene: 'Cảnh',
    status: 'Trạng thái',
    moreOption: 'Nhiều hơn',
    next: 'Tiếp',
    byUser: 'bởi',
    pinCodeUsed: 'Mã pin đã được sử dụng',
    masterCode: 'master code',
    modeActive: 'Chế độ',
    sortDevices: 'Sắp xếp thiết bị',
    activity: 'Hoạt động',
    logDetail: 'Chi tiết',
    typeExecution: {
      onOff: 'Bật tắt',
      colorSpectrum: 'Màu sắc',
      coldWarmColor: 'Độ lạnh, nhạt của màu',
      brightness: 'Độ sáng',
      modeActive: 'Chế độ'
    },
    chooseTypeControl: 'Chọn kiểu điều khiển',
    sourceControl: {
      app: 'Ứng dụng',
      rule: 'Rule',
      scene: 'Cảnh',
      physical: 'Vật lý',
      device: 'Thiết bị',
      hand: 'Tay',
      schedule: 'Lịch',
      controlBy: 'Điều khiển bởi',
      from: 'từ',
      group: 'Nhóm'
    },
    normalType: 'Thường',
    selectCamera: 'Chọn camera',
    titleMeshNetworkReconfig: 'Tìm lại mạng',
    cameraPreview: 'Kết nối Camera',
    removeCameraPreview: 'Không dùng camera',
    ruleInfo: 'Thông tin rule',
    sceneInfo: 'Thông tin cảnh',
    groupInfo: 'Thông tin nhóm'
  }
});

export default langs;
